# Generated by Django 3.2.7 on 2022-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220407_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mnumber',
            new_name='mobile_number',
        ),
    ]
