# Generated by Django 3.2.7 on 2022-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220412_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(null=True, upload_to='account/%y')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='video',
        ),
    ]
