# Generated by Django 3.2.7 on 2022-04-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
