# Generated by Django 3.2.7 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(null=True, upload_to='account/%y'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
