# Generated by Django 3.2.7 on 2022-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='video',
            field=models.FileField(null=True, upload_to='account/%y'),
        ),
    ]
